import serie40 from "../img/serie_40_elipse.png";
import serie75 from "../img/serie_75_blindee.png";
import serie45 from "../img/serie_ex45_prestige.png";
import serietw60 from "../img/serie_tw60_confort.png";
import serie22 from "../img/serie_22_ellipse.png";
import serie67 from "../img/serie_67_ellipse.png";
import serie160 from "../img/serie_160_confort.png";
import serieex60 from "../img/serie_ex60_prestige_ligne_droite.png";
import serieex60el from "../img/serie_ex60_prestige_ligne_elliptique.png";
import seriets60 from "../img/serie_ts60_confort.png";
import serie52horrptvep from "../img/serie52_horizon_rpt_vep.png";
import serie52horvec from "../img/serie52_horizon_vec.png";
import serie52horth from "../img/serie52_horizon_th.png";
import serie84evo from "../img/serie84_evoulution_vec.png";
import cloisonsjointcreux from "../img/cloisons_lisses_joint_creux.png";
import cloisonsstructure from "../img/cloisons_lisses_structure_visible.png";
import serievolets from "../img/serie-volets-coulissants.png";
import seriegrille from "../img/serie-grille-de-ventilation.png";
import serie15ellipse from "../img/serie15_ellipse.png";
import seriebrise from "../img/serie-brise-soleil.png";
import fenetrejalousie from "../img/fenetre_jalousie_tpr.png";
import pergolebioclimatique from "../img/pergola_bioclimatique_tpr19.png";
import gardecorps from "../img/garde_corps_encastre_gs.png";
import moteur1 from "../img/kit_de_remplacement.png";
import moteur2 from "../img/kitdemotorisation.png";
import moteur3 from "../img/rs100_solar_io.png";
import p1 from "../img/alba_key_cremone.png";
import p2 from "../img/micro_key_cremone.png";
import p3 from "../img/luna_key_cremone130_external_fixing.png";
import p4 from "../img/handlinga_and_flat_catch_handle.png";
import p5 from "../img/connector9mm.png";

// 1 : Battante / 2 : Rideaux / 3 : Coulissante / 4 : Autres
export const ProductList = [
  {
    id: 1,
    type: 2,
    productType: 1,
    img: serie52horrptvep,
    name: "SÉRIE 52 HORIZON+ RPT VEP",
    title: "Système de Façade Rideau à Rupture de Pont Thermique VEP",
    describtion1:
      "- Structure constituée de meneaux verticaux et de traverses horizontales de meme section et de largeur intérieure visible de 52 mm.",
    describtion2:
      "- Panneaux de remplissage “visions ou opaques” en profilé multi-chambre à rupture de pont thermique assemblés par une double équerre à sertir en aluminium et étanchés par une colle spéciale.",
    describtion3:
      "- Assemblage des traverses sur meneaux assuré par des blocs spéciaux en aluminium et des bouchons de finition élastique absorbant les effets de dilatation des traverses.",
    describtion4:
      "- Panneaux fixes reposant sur des cales “supports panneaux” et tenus à l’ossature par des blocs à pions de qualité sur les côtés latéraux du cadre.",
    describtion5:
      "- Double vitrage en panneaux vision de 24 à 28 mm d’épaisseur et d’un poids maxi de 130kg.",
    describtion6:
      "- Visserie et boulonnerie entièrement en acier inoxydable anti-corrosion.",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 2,
    type: 2,
    productType: 1,
    img: serie52horvec,
    name: "SÉRIE 52 HORIZON+ VEC",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 3,
    type: 2,
    productType: 1,
    img: serie52horth,
    name: "SÉRIE 52 HORIZON+ TH",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },

  {
    id: 4,
    type: 1,
    productType: 1,
    img: serie40,
    name: "SÉRIE 40 ELLIPSE",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 5,
    type: 1,
    productType: 1,
    img: serie75,
    name: "SÉRIE 75 BLINDÉE",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 6,
    type: 1,
    productType: 1,
    img: serie45,
    name: "SÉRIE EX45 PRESTIGE",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 7,
    type: 1,
    productType: 1,
    img: serietw60,
    name: "SÉRIE TW60 CONFORT",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 8,
    type: 3,
    productType: 1,
    img: serie22,
    name: "SÉRIE 22 ELLIPSE",
    title: "Fenêtres et Porte-Fenêtres Coulissantes",
    describtion1: "- Dormant d’épaisseur 40 mm.",
    describtion2: "- Ouvrant d’épaisseur 26 mm.",
    describtion3: "- Simple vitrage: 6, 8 mm.",
    describtion4: "- Double vitrage: 18 mm.",
    describtion5: "- Fermetures encastrées.",
    describtion6: "- Galets simples ou doubles réglables de 90kg.",
    describtion7: "- Joints d’étanchéité en EPDM d’excellente qualité.",
    describtion8: "- Double joints brosse fin-seal.",
  },
  {
    id: 9,
    type: 3,
    productType: 1,
    img: serie67,
    name: "SÉRIE 67 ELLIPSE",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 10,
    type: 3,
    productType: 1,
    img: serie160,
    name: "SÉRIE 160 CONFORT",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 10,
    type: 3,
    productType: 1,
    img: serieex60,
    name: "SÉRIE EX60 PRESTIGE LIGNE DROITE",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 10,
    type: 3,
    productType: 1,
    img: serieex60el,
    name: "SÉRIE EX60 PRESTIGE LIGNE ELLIPTIQUE",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 10,
    type: 3,
    productType: 1,
    img: seriets60,
    name: "SÉRIE TS60 CONFORT",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 11,
    type: 2,
    productType: 1,
    img: serie84evo,
    name: "SÉRIE 84 EVOLUTION VEC",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 12,
    type: 4,
    productType: 1,
    img: cloisonsjointcreux,
    name: "SÉRIE 16 ELLIPSE VISIBLE",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 13,
    type: 4,
    productType: 1,
    img: cloisonsstructure,
    name: "SÉRIE 16 ELLIPSE CREUX",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 14,
    type: 4,
    productType: 1,
    img: serievolets,
    name: "SÉRIE VOLETS COULISSANTS",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 15,
    type: 4,
    productType: 1,
    img: seriegrille,
    name: "SÉRIE GRILLE DE VENTILATION",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 16,
    type: 4,
    productType: 1,
    img: serie15ellipse,
    name: "SÉRIE 15 ELLIPSE",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 17,
    type: 4,
    productType: 1,
    img: seriebrise,
    name: "SÉRIE BRISE SOLEIL",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 18,
    type: 4,
    productType: 1,
    img: fenetrejalousie,
    name: "FENÊTRE JALOUSIE TPR",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 19,
    type: 4,
    productType: 1,
    img: pergolebioclimatique,
    name: "PERGOLA BIOCLIMATIQUE TPR 19",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 20,
    type: 4,
    productType: 1,
    img: gardecorps,
    name: "GARDE CORPS ENCASTRÉ GS 85",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 21,
    type: 1,
    productType: 2,
    img: moteur1,
    name: "KIT DE Remplacement",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 22,
    type: 2,
    productType: 2,
    img: moteur2,
    name: "KIT DE Motorisation",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 23,
    type: 3,
    productType: 2,
    img: moteur3,
    name: "RS 100 SOLAR IO",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 24,
    type: 1,
    productType: 3,
    img: p1,
    name: "alba_key_cremone",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 25,
    type: 2,
    productType: 3,
    img: p2,
    name: "micro_key_cremone",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 26,
    type: 3,
    productType: 3,
    img: p3,
    name: "luna_key_cremone130_external_fixing",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 27,
    type: 4,
    productType: 3,
    img: p4,
    name: "handlinga_and_flat_catch_handle",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
  {
    id: 28,
    type: 2,
    productType: 3,
    img: p5,
    name: "connector9mm",
    describtion1: "",
    describtion2: "",
    describtion3: "",
    describtion4: "",
    describtion5: "",
    describtion6: "",
    describtion7: "",
    describtion8: "",
  },
];
